[book]
authors = ["Ben Falk"]
language = "en"
multilingual = false
src = "src"
title = "My Journey Through Space and Time"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/benfalk/benfalk"
edit-url-template = "https://github.com/benfalk/benfalk/edit/main/{path}"
no-section-label = true
fold = { enable = true, level = 1 }

[output.html.playground]
editable = true
copyable = true
line-numbers = true
runnable = false

[preprocessor.journal]

[preprocessor.journal.topics.snippet]
path_mapping = "{{kebabCase lang}}/{{kebabCase title}}"
template = """

## {{titleCase title}}

```{{lang}}
```
"""
[preprocessor.journal.topics.snippet.variables]
title = { required = true }
lang = { required = true }

[preprocessor.anchors-aweigh]
after = ["journal"]

[preprocessor.anchors-aweigh.templates]
snippet = """
```rust
{{contents}}
```
"""

[preprocessor.anchors-aweigh.queries.rust]
mod = """
(mod_item
  name: (identifier) @name (#eq? @name "{{name}}")
  body: (declaration_list) @match
 )
"""
